#include <bits/stdc++.h>
#define mod 1000000007
#define ll long long
using namespace std;

void solve() {
  int p_c; // final power of chef
  int p_r; // final power of rick
  cin >> p_c >> p_r;

  // Goal of each player is to generate a positive integer
  // such that its power is equal to his final power

  // The one that generates the integer with fewer digits wins
  // If both have same number of digit, then Rick wins automatically
  
  // Output
  // Space separated
  // 1 for Chef win or 0 for Rick win
  // and the number of digits generated by the winner
}

int main() {
  int T;
  cin >> T;
  while (T--) {
    solve();
  }
  return 0;
}

